First version of the bot
zkBob/cdp-nft-liqbot pull request #2
Opened 2022-12-22 19:24 UTC by YusupovAI

2022-12-23 13:48 UTC, AlexSaplin requested changes

2022-12-23 13:48 UTC, AlexSaplin commented on src/Bot.sol
> +        pools = pools_;
Let's implement methods that allow adding (necessary) and removing (arguably) pools

2022-12-26 06:56 UTC, k1rill-fedoseev commented on src/Bot.sol
> +            pool.flash(address(this), flashData.debt, 0, data);
I have just realised the problem with usage of uniswap flash loans.
If we take the flash loan from BOB/USDC pool, then we won't be able to swap through that pool inside of a callback.

Probably the best way is to go with a flash mint module then (https://eips.ethereum.org/EIPS/eip-3156, https://github.com/zkBob/zkbob-contracts/blob/2dd5fcccc096112a7fda5905928b46309ad98a09/src/minters/FlashMinter.sol)

2022-12-26 06:56 UTC, k1rill-fedoseev commented on src/Bot.sol
> +        require(debt >= flashData.cdp.calculateVaultAdjustedCollateral(flashData.vaultId), "vault is healthy");
This is already checked in vault contract, right? I don't think we need to check it twice.

2022-12-26 06:56 UTC, k1rill-fedoseev commented on src/Bot.sol
> +        uint256 debt = flashData.cdp.getOverallDebt(flashData.vaultId);
Should we set` flashData.debt` to `debt`, as it is constantly increasing and will be already different when transaction makes it through?

2022-12-26 06:56 UTC, k1rill-fedoseev commented on src/Bot.sol
> +            require(actualNfts[i] == flashData.nfts[i], "wrong NFT list");
If we will receive a different set of nfts, then `closeUniV3Position` will fail for some of them, so checking the entire list once again seems a bit redundant.

2022-12-26 06:56 UTC, k1rill-fedoseev commented on src/Bot.sol
> +        token.transfer(recepient, earnings);
In case the some other erc20/erc721 tokens will be left in the contract after execution, let's add a method for claiming them later.
For that, we will also need to set a contract owner.

2022-12-26 07:38 UTC, YusupovAI commented on src/Bot.sol
> +            pool.flash(address(this), flashData.debt, 0, data);
Yes, there is a problem.
Is flash mint going to be deployed in the nearest future?

2022-12-26 07:46 UTC, k1rill-fedoseev commented on src/Bot.sol
> +            pool.flash(address(this), flashData.debt, 0, data);
Not in the nearest, but we can deploy it together with CDP once its ready.

For tests, I think you can still deploy it locally in forked env and whitelist it in the token contract.

Something like this usually works fine for me:
```solidity
FlashMinter minter = new FlashMinter(...);
vm.etch(bob.owner(), "");
vm.prank(bob.owner());
bob.updateMinter(address(minter), true, true);
```

2022-12-27 07:41 UTC, k1rill-fedoseev approved these changes
lgtm

2022-12-27 07:41 UTC, k1rill-fedoseev commented on src/Bot.sol
> +        address recepient
```suggestion
        address recipient
```

2022-12-27 12:38 UTC, AlexSaplin approved these changes

2022-12-28 13:04 UTC, merged